# Generated by Django 3.1.7 on 2021-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210501_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_desc',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
