# Generated by Django 3.1.7 on 2021-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_long_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Display', models.CharField(max_length=50)),
                ('front_cam', models.CharField(max_length=50)),
                ('rear_cam', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
            ],
        ),
    ]
