# Generated by Django 3.1.7 on 2021-05-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='product_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
