# Generated by Django 3.1.7 on 2021-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210517_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to="'shop/images'"),
            preserve_default=False,
        ),
    ]
