# Generated by Django 3.1.7 on 2021-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
