# Generated by Django 3.1.7 on 2021-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210523_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_url',
            new_name='img_url1',
        ),
        migrations.AddField(
            model_name='product',
            name='img_url2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
