# Generated by Django 3.1.7 on 2021-06-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210523_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Product2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('img_url1', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_url2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_desc',
        ),
    ]
